create table vehicles
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp,
    deleted    boolean not null,
    updated_at timestamp,
    user_iin varchar(12),
    grnz varchar(255),
    vehicle_type varchar(255),
    FOREIGN KEY (user_iin) REFERENCES users (uin)
);

create table buses
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp,
    deleted    boolean not null,
    updated_at timestamp,
    user_iin varchar(12),
    grnz varchar(255),
    vehicle_type varchar(255),
    seats int,
    FOREIGN KEY (user_iin) REFERENCES users (uin)
);

create table cars
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp,
    deleted    boolean not null,
    updated_at timestamp,
    user_iin varchar(12),
    grnz varchar(255),
    vehicle_type varchar(255),
    engine_capacity int,
    FOREIGN KEY (user_iin) REFERENCES users (uin)
);

create table freights
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp,
    deleted    boolean not null,
    updated_at timestamp,
    user_iin varchar(12),
    grnz varchar(255),
    vehicle_type varchar(255),
    load_capacity int,
    FOREIGN KEY (user_iin) REFERENCES users (uin)
);


create table taxes
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp,
    deleted    boolean not null,
    updated_at timestamp,
    status    int not null,
    amount int,
    vehicle_id bigint,
    FOREIGN KEY (vehicle_id) REFERENCES vehicles (id)
);

alter table vehicles
    owner to postgres;

alter table taxes
    owner to postgres;
