version: "3.9"

services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "12561:12561"
    restart: always
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    depends_on:
      - eureka-server
      - postgres
    ports:
      - "12582:12582"
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:12561/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auto_life_prod
    restart: always
    networks:
      - app-network

  fine-car-service:
    build: ./fine-car-service
    ports:
      - "12584:12584"
    depends_on:
      - eureka-server
      - postgres
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:12561/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auto_life_prod
    restart: always
    networks:
      - app-network

  tax-service:
    build: ./tax-service
    depends_on:
      - eureka-server
      - postgres
    ports:
      - "12594:12594"
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:12561/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auto_life_prod
    restart: always
    networks:
      - app-network

  card-service:
    build: ./card-service
    depends_on:
      - eureka-server
      - postgres
    ports:
      - "12501:12501"
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:12561/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auto_life_prod
    restart: always
    networks:
      - app-network

  payment-service:
    build: ./payment-service
    depends_on:
      - eureka-server
      - postgres
    ports:
      - "12577:12577"
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:12561/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auto_life_prod
    restart: always
    networks:
      - app-network

  shop-service:
    build: ./shop-service
    depends_on:
      - eureka-server
      - postgres
    ports:
      - "12599:12599"
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:12561/eureka
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auto_life_prod
    restart: always
    networks:
      - app-network

  api-gateway:
    build: ./api-gateway
    depends_on:
      - eureka-server
      - auth-service
      - fine-car-service
      - tax-service
      - payment-service
      - card-service
      - shop-service
    environment:
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://eureka-server:12561/eureka
    ports:
      - "12565:12565"
    restart: always
    networks:
      - app-network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auto_life_prod
    ports:
      - "12534:12534"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
