server:
  port: 12565

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**,/api/v1/test/**, /api/user/**
            - Method=POST,GET
        - id: car
          uri: lb://fine-car-service
          predicates:
            - Path=/api/fines/**
            - Method=GET,POST
        - id: vehicle
          uri: lb://tax-service
          predicates:
            - Path=/api/vehicles/**, /api/taxes/**
            - Method=POST,GET
        - id: card
          uri: lb://card-service
          predicates:
            - Path=/api/cards/**, /api/transactions/**
            - Method=POST,GET
        - id: payment
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**, /api/accommodations/**
            - Method=POST,GET
        - id: shop
          uri: lb://shop-service
          predicates:
            - Path=/api/shop/items/**, /api/shop/images/**
            - Method=POST,GET

eureka:
  client:
    service-url:
      defaultZone: http://localhost:12561/eureka

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"