server:
  port: 12565

# id приложения
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**,/api/v1/test
            - Method=POST,GET
        - id: car
          uri: lb://fine-car-service
          predicates:
            - Path=/api/fine
            - Method=GET
        - id: vehicle
          uri: lb://vehicle-service
          predicates:
            - Path=/api/vehicle/**
            - Method=POST


# url для регистрации микросервисов
eureka:
  client:
    service-url:
      defaultZone: http://localhost:12561/eureka

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"