server:
  port: 12584

# id приложения
spring:
  application:
    name: fine-car-service

# url для регистрации микросервисов
eureka:
  client:
    service-url:
      defaultZone: http://localhost:12561/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: "*"

