-- auto-generated definition
create table users
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp,
    deleted    boolean not null,
    updated_at timestamp,
    first_name varchar(255),
    last_name  varchar(255),
    mid_name   varchar(255),
    password   varchar(255),
    phone      varchar(255)
        constraint uk_du5v5sr43g5bfnji4vb8hg5s3
            unique,
    uin        varchar(255)
        constraint uk_89u3i6agv520oej5ijbblxvpb
            unique
);

alter table users
    owner to postgres;

