drop table users cascade;
drop table cards cascade;
drop table vehicles cascade;
drop table taxes cascade;
drop table transactions cascade;
drop table services cascade;
drop table fines cascade;
drop table images cascade;
drop table items cascade;
drop table items_images cascade;

-- auto-generated definition
create table users
(
    id         uuid
        primary key,
    created_at timestamp,
    deleted    boolean not null,
    updated_at timestamp,
    first_name varchar(255),
    last_name  varchar(255),
    mid_name   varchar(255),
    password   varchar(255),
    phone      varchar(255)
        constraint uk_du5v5sr43g5bfnji4vb8hg5s3
            unique,
    uin        varchar(255)
        constraint uk_89u3i6agv520oej5ijbblxvpb
            unique
);

create table cards
(
    id         uuid
        primary key,
    created_at timestamp,
    deleted    boolean not null,
    updated_at timestamp,
    full_name varchar(255),
    card_number varchar(20)
        constraint card_number_unique
            unique,
    card_month int,
    card_year int,
    cvv varchar(255),
    amount decimal,
    user_id uuid
        constraint user_not_null
            NOT NULL
);


alter table users
    owner to postgres;

alter table cards
    owner to postgres;

-- generated by default as identity
create table vehicles
(
    id         uuid
        primary key,
    created_at timestamp,
    deleted    boolean not null,
    updated_at timestamp,
    user_iin varchar(12),
    grnz varchar(255)
        constraint grnz_unique
            unique,
    vehicle_type varchar(255),
    vehicle_key varchar(255),
    vehicle_value varchar(255)
);

alter table vehicles
    owner to postgres;

-- generated by default as identity
create table taxes
(
    id         uuid
        primary key,
    created_at timestamp,
    deleted    boolean not null,
    updated_at timestamp,
    user_iin varchar(12),
    grnz varchar(255),
    vehicle_type varchar(255),
    amount decimal,
    paid Boolean
);

alter table taxes
    owner to postgres;

create table transactions
(
    id         uuid
        primary key,
    created_at timestamp,
    service_id uuid,
    service_description varchar(255),
    service_amount decimal,
    user_id uuid
        constraint user_not_null_1
            NOT NULL
);

alter table transactions
    owner to postgres;


ALTER TABLE cards ALTER COLUMN cvv TYPE varchar(3);
ALTER TABLE taxes ADD currency varchar(20);

ALTER TABLE transactions ADD reference_id uuid;
ALTER TABLE transactions ADD currency varchar(20);

create table services
(
    id         uuid
        primary key,
    created_at timestamp,
    deleted    boolean not null,
    updated_at timestamp,
    service_name varchar(255)
);


create table fines
(
    id         uuid
        primary key,
    user_iin varchar(12),
    fine_description varchar(255),
    grnz varchar(255),
    vehicle_type varchar(255),
    amount_MCI int,
    paid Boolean
);

INSERT INTO fines (id, user_iin, fine_description, grnz, vehicle_type, amount_MCI, paid) values ('07562ddc-a394-4f12-b356-6e1b2f87b97a', '000000000003', 'Driving a vehicle by a driver who does not have a driver''s license or a temporary license issued in exchange for a driver''s license for the right to drive', 'dsaz', 'BUS', 5, false),
                                                                                                ('96c105c2-743e-4d51-9389-63a829dadea1', '000000000003', 'Evasion from concluding a contract of compulsory insurance', 'ds321az', 'CAR', 10, false),
                                                                                                ('bc7774f0-6ec4-4990-b535-e28f26f9efec', '000000000001', 'Exceeding the speed limit by 20-40 km/h', 'd21az', 'FREIGHT', 10, false),
                                                                                                ('64d6479a-8543-47a9-b246-034ffb6755ff', '000000000001', 'Driving at a traffic light signal or a traffic controller''s prohibition gesture', 'd21azdsa', 'CAR', 10, false);

alter table fines
    owner to postgres;


create table images
(
    id         uuid
        primary key,
    name varchar(255),
    type varchar(255),
    data oid
);

create table items
(
    id         uuid
        primary key,
    created_at timestamp,
    deleted    boolean not null,
    updated_at timestamp,
    amount int,
    title varchar(255),
    price decimal
);

create table items_images
(
    item_id       uuid not null
        constraint fkknbxvg28cl7okidd4of94mjuh
            references items,
    image_id uuid not null
        constraint uk_fo9ensuuxidpqnww8a9qe8yyo
            unique
        constraint fk99rxpfnwk9o89ldate8hrb7c1
            references images
);

alter table images
    owner to postgres;

alter table items
    owner to postgres;

alter table items_images
    owner to postgres;




