create table transactions
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp,
    service_id bigint,
    service_type varchar(255),
    service_description varchar(255),
    service_amount int,
    user_id bigint
        constraint user_not_null_1
            NOT NULL
);

alter table transactions
    owner to postgres;
