-- generated by default as identity
create table vehicles
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp,
    deleted    boolean not null,
    updated_at timestamp,
    user_iin varchar(12),
    grnz varchar(255)
        constraint grnz_unique
            unique,
    vehicle_type varchar(255),
    vehicle_key varchar(255),
    vehicle_value varchar(255)
);

alter table vehicles
    owner to postgres;
