create table fines
(
    id         bigint generated by default as identity
        primary key,
    user_iin varchar(12),
    fine_description varchar(255),
    grnz varchar(255),
    vehicle_type varchar(255),
    amount_MCI int,
    paid Boolean
);

INSERT INTO fines (user_iin, fine_description, grnz, vehicle_type, amount_MCI, paid) values ('000000000003', 'Driving a vehicle by a driver who does not have a driver''s license or a temporary license issued in exchange for a driver''s license for the right to drive', 'dsaz', 'BUS', 5, false),
                         ('000000000003', 'Evasion from concluding a contract of compulsory insurance', 'ds321az', 'CAR', 10, false),
                         ('000000000001', 'Exceeding the speed limit by 20-40 km/h', 'd21az', 'FREIGHT', 10, false),
                         ('000000000001', 'Driving at a traffic light signal or a traffic controller''s prohibition gesture', 'd21azdsa', 'CAR', 10, false);

alter table fines
    owner to postgres;
