-- generated by default as identity
create table buses
(
    id         uuid primary key,
    created_at timestamp,
    deleted    boolean not null,
    updated_at timestamp,
    user_iin varchar(12),
    grnz varchar(255)
        constraint grnz_unique1
            unique,
    vehicle_type varchar(255),
    seats int
);

create table cars
(
    id         uuid primary key,
    created_at timestamp,
    deleted    boolean not null,
    updated_at timestamp,
    user_iin varchar(12),
    grnz varchar(255)
        constraint grnz_unique2
            unique,
    vehicle_type varchar(255),
    engine_capacity int
);

create table freights
(
    id         uuid primary key,
    created_at timestamp,
    deleted    boolean not null,
    updated_at timestamp,
    user_iin varchar(12),
    grnz varchar(255)
        constraint grnz_unique3
            unique,
    vehicle_type varchar(255),
    load_capacity int
);

alter table buses
    owner to postgres;

alter table cars
    owner to postgres;

alter table freights
    owner to postgres;
